<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace>test</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="ScottBrady.IdentityModel" Version="4.1.0" />
      <PackageReference Include="System.Security.Cryptography.Algorithms" Version="4.3.1" />
    </ItemGroup>

</Project>
